platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'BWiOSStudy' do

  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '3.0.15.1'
  pod 'YYCategories', '1.0.4'
  pod 'SVProgressHUD', '2.2.5'
  pod 'YYText'
  
  pod 'Tencent-MapSDK', '4.3.9.2'  # 腾讯地图

  target 'BWiOSStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWiOSStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
