# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BWObjective-CStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'MJExtension', '3.2.2'

  # Pods for BWObjective-CStudy

end
