platform :ios, '8.0'

target 'BWiOSStudy' do

  pod 'Masonry', '~> 1.1.0'

  target 'BWiOSStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWiOSStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
